// src/integrations/react/example.jsx
import { useKeyframes } from 'ziko-keyframes/react';
import {bounce} from "ziko-keyframes";
const AnimatedComponent = () => {
  const node = useKeyframes(() => bounce(1000, 2, 'ease'));
  return (
    <div
      ref={node}
      style={{ color: 'darkblue', fontSize: '24px' }}
    >
      Hello from React with Animation
    </div>
  );
};

export default AnimatedComponent;

// src/integrations/vue/example.vue
<template>
    <div ref="animatedElement" style="color: darkblue; font-size: 24px">
      Hello from Vue.js with Animation
    </div>
  </template>
<script setup>
  import { useKeyframes } from 'ziko-keyframes/vue';
  import { bounce } from 'ziko-keyframes';
  const getBounceAnimation = () => bounce(1000, 2, 'ease');
  const animatedElement = useKeyframes(getBounceAnimation);
</script>
