// src/integrations/preact/example.jsx
import { useKeyframes } from 'ziko-keyframes/preact';
import {bounce} from "ziko-keyframes";
const getBounceAnimation = () => bounce(3000, Infinity, 'ease');
export function App() {
  const [count, setCount] = useState(0);
  const node = useKeyframes(getBounceAnimation);
  return (
    <div
      ref={node}
      style={{ color: 'darkblue', fontSize: '24px' }}
    >
      Hello from Preact with Animation
    </div>
  );
}

// src/integrations/vue/example.vue
<template>
    <div ref="animatedElement" style="color: darkblue; font-size: 24px">
      Hello from Vue.js with Animation
    </div>
  </template>
<script setup>
  import { useKeyframes } from 'ziko-keyframes/vue';
  import { bounce } from 'ziko-keyframes';
  const getBounceAnimation = () => bounce(1000, 2, 'ease');
  const animatedElement = useKeyframes(getBounceAnimation);
</script>
